name: Quality Gate

on:
  pull_request:
    branches: [main]

jobs:
  fta-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - name: Generate current FTA JSON
        run: pnpm run complexity:json
      - name: Generate base FTA JSON
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          git worktree add ../base "$BASE_SHA"
          pushd ../base
          pnpm install
          pnpm run complexity:json
          popd
          mkdir -p reports
          cp ../base/reports/fta.json reports/fta.base.json
          git worktree remove ../base --force
      - name: Compute changed TS files
        id: diff
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          CHANGED=$(git diff --name-only "$BASE_SHA".."$HEAD_SHA" -- 'src/**/*.ts' 'src/**/*.tsx' | tr '\n' ',' | sed 's/,$//')
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT
      - name: Enforce thresholds
        env:
          FTA_HARD_CAP: ${{ vars.FTA_HARD_CAP || 50 }}
          FTA_DELTA_PCT: ${{ vars.FTA_DELTA_PCT || 10 }}
        run: node scripts/compare-fta.mjs --current=reports/fta.json --base=reports/fta.base.json --changed='${{ steps.diff.outputs.changed }}'
